# Generated by Django 4.1.4 on 2023-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='Confirmpassword',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='Password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
