# Generated by Django 4.1.4 on 2023-03-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=10)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Idnumber', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Sign', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='Source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
