# Generated by Django 4.1.4 on 2023-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='bank_loan',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='emi',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='fees',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
